labatt/force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

labatt/force-app/main/default/objects/Service_Order__c/Service_Order__c.object-meta.xml
<CustomObject>
    <label>Service Order</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Service Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

labatt/force-app/main/default/objects/Service_Order__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Service Orders</relationshipLabel>
    <relationshipName>Service_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

labatt/force-app/main/default/classes/UpdateServiceOrderAttachmentsBatch.cls
public class UpdateServiceOrderAttachmentsBatch implements Database.Batchable<sObject> {
    public final String query; 

    public UpdateServiceOrderAttachmentsBatch(Set<Id> orderIds) {
        List<Id> ordLst = new List<Id>();
        ordLst.addAll(orderIds);
        query = 'select id from order__c where ID in :'+ordLst;
    }

    public Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<Object> scope){
        Set<Id> soIds = new Set<Id>();
        List<Id> soIdList = new List<Id>();
        //Filter Service_Orders 
        for(Order__c o: [SELECT ID, (select id from Service_Orders__r order by lastModifiedDate desc) FROM Order__c where Id IN :(List<Id>)scope]){
            if(null != o.Service_Orders__r && o.Service_Orders__r.size() > 0){
                for(Service_Order__c so: o.Service_Orders__r){
                    soIds.add(so.Id);
                }
                soIdList.addAll(soIds); 
                soIdList.remove(0);
                soIdList.remove(0);
            }
        }
        
        //Delete Attachments
        if(soIdList.size() > 0){
            List<Attachment> attToDelete = new List<Attachment>();
            for(Attachment at: [SELECT ID, Name from attachment where parentId IN :soIdList]){
                if(at.Name.contains('.'))
                    if(at.Name.subStringAfter('.').toUpperCase() == 'JPEG'){
                        attToDelete.add(at);
                    }
            }
        if(attToDelete.size() > 0)
            delete attToDelete;
        }
    }

    public void finish(Database.BatchableContext bc){

    }


}