labatt/force-app/main/default/objects/Logs__c/Logs__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Payload Logs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

labatt/force-app/main/default/objects/Logs__c/fields/JSON_response__c.field-meta.xml
<CustomField>
    <fullName>JSON_response__c</fullName>
    <label>JSON response</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

labatt/force-app/main/default/classes/GoogleAPIService.cls
public with sharing class GoogleAPIService {
   public static void getContacts(){
       HttpRequest req = new HttpRequest();
       Http http = new Http();
       req.setMethod('GET');
       req.setEndpoint('callout:Google_People_API/v1/people/c1150104659039327954?personFields=names,emailAddresses');
       HttpResponse res = http.send(req);
       Logs__c log = new Logs__c(JSON_response__c = res.getBody(), Status_Code__c=String.valueOf(res.getStatusCode()));
       insert log;

   }


}